apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ocs.fullname" . }}
  labels:
    {{- include "ocs.labels" . | nindent 4 }}
data:
{{- range $key, $val := .Values.secret.data }}
  {{ $key }}: {{ $val | b64enc }}
{{- end -}}